# syntax=docker/dockerfile:1

ARG NODE_VERSION=22.19.0

FROM node:${NODE_VERSION}-alpine

# Set env variables
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Use corepack to handle pnpm
RUN corepack enable

# Set working directory
WORKDIR /usr/src/app

# Copy monorepo root files and workspace config
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Copy frontend files over
COPY javascript-example-frontend/ ./javascript-example-frontend

# Copy this projects files over and any other dependencies this service needs

# Install dependencies for this project
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
  pnpm install --filter "@javascript-example-frontend..." --frozen-lockfile

# Expose the port used by the Vite development server
EXPOSE 5173

# Start the dev server
CMD ["pnpm", "--filter", "@javascript-example-frontend", "run", "dev"]
