name: javascript-example
services:
  javascript-example-database:
    extends:
        file: compose.common.yaml
        service: javascript-example-database
  javascript-example-redis:
    extends:
        file: compose.common.yaml
        service: javascript-example-redis
  javascript-example-backend-api:
    extends:
        file: compose.common.yaml
        service: javascript-example-backend-api
    build:
      context: .
      dockerfile: javascript-example-backend/projects/api/Dockerfile.dev
    environment:
      NODE_ENV: development
    depends_on:
      javascript-example-database:
        condition: service_started
  javascript-example-backend-authority:
    extends:
      file: compose.common.yaml
      service: javascript-example-backend-authority
    build:
      context: .
      dockerfile: javascript-example-backend/projects/authority/Dockerfile.dev
    environment:
      NODE_ENV: development
    depends_on:
      javascript-example-database:
        condition: service_started
      javascript-example-redis:
        condition: service_started
  javascript-example-db-tools:
    container_name: javascript-example-db-tools
    build:
      context: .
      dockerfile: javascript-example-backend/projects/common/Dockerfile.dev
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - ./javascript-example-backend/projects/common/src/database:/usr/src/app/javascript-example-backend/projects/common/src/database
      - ./javascript-example-backend/projects/common/dist:/usr/src/app/javascript-example-backend/projects/common/dist
      - ./javascript-example-backend/projects/common/generated:/usr/src/app/javascript-example-backend/projects/common/generated
    ports:
      - "5555:5555"
    secrets:
      - postgres_password
    depends_on:
      javascript-example-database:
        condition: service_started
  javascript-example-redis-insight:
    container_name: javascript-example-redis-insight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      javascript-example-redis:
        condition: service_started
  javascript-example-frontend:
    extends:
        file: compose.common.yaml
        service: javascript-example-frontend
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: javascript-example-frontend/Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: javascript-example-frontend
          target: /usr/src/app/javascript-example-frontend
          ignore:
          - node_modules/
          - dist/
          - package.json
          - Dockerfile.dev
        - action: rebuild
          path: javascript-example-frontend/package.json
        - action: rebuild
          path: pnpm-lock.yaml
        - action: rebuild
          path: javascript-example-frontend/Dockerfile.dev
secrets:
  postgres_password:
    file: secrets/postgres_password.txt
volumes:
  database:
  redis: