name: javascript-example
services:
  javascript-example-database:
    container_name: javascript-example-database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "sample"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql
    secrets:
      - postgres_password 
  javascript-example-redis:
    container_name: javascript-example-redis
    image: redis:8-alpine
    restart: always
    ports: 
      - 6379:6379
    volumes:
      - redis:/data
  javascript-example-backend-api:
    container_name: javascript-example-backend-api
    build:
      context: .
      dockerfile: javascript-example-backend/projects/api/Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      AUTHORITY_URL: http://javascript-example-backend-authority:3001
      ISSUER: http://localhost:3001
    secrets:
      - postgres_password
  javascript-example-backend-authority:
    container_name: javascript-example-backend-authority
    build:
      context: .
      dockerfile: javascript-example-backend/projects/authority/Dockerfile
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      REDIS_URL: redis://javascript-example-redis:6379
    depends_on:
      - javascript-example-redis
    secrets:
      - postgres_password 
  javascript-example-frontend:
    container_name: javascript-example-frontend
    build:
      context: .
      dockerfile: javascript-example-frontend/Dockerfile
secrets:
  postgres_password:
    file: secrets/postgres_password.txt
volumes:
  database:
  redis: