packages:
  - javascript-example-backend
  - javascript-example-backend/projects/*
  - javascript-example-frontend

catalogs:
  backend:
    '@eslint/js': ^9.39.1
    '@inversifyjs/http-core': ^4.6.0
    '@inversifyjs/http-express-v4': ^4.6.0
    '@types/express': ^5.0.5
    '@types/node': ^24.10.1
    '@types/swagger-jsdoc': ^6.0.4
    '@types/swagger-ui-express': ^4.1.8
    eslint: ^9.39.1
    eslint-plugin-unused-imports: ^4.3.0
    express: ^5.1.0
    globals: ^16.5.0
    inversify: ^7.10.4
    jiti: ^2.6.1
    reflect-metadata: ^0.2.2
    swagger-jsdoc: ^6.2.8
    swagger-ui-express: ^5.0.1
    typescript: ^5.9.3
    typescript-eslint: ^8.48.0

ignoredBuiltDependencies:
  - '@scarf/scarf'

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
