packages:
  - javascript-example-backend
  - javascript-example-backend/*
  - javascript-example-frontend

ignoredBuiltDependencies:
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
