# syntax=docker/dockerfile:1

ARG NODE_VERSION=22.19.0

FROM node:${NODE_VERSION}-alpine

# Set env variables
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Use corepack to handle pnpm
RUN corepack enable

# Set working directory
WORKDIR /usr/src/app

# Copy monorepo root files and workspace config
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Copy shared backend files over
COPY javascript-example-backend/*.* ./javascript-example-backend/

# Copy this projects files over and any other dependencies this service needs

COPY javascript-example-backend/projects/api/ ./javascript-example-backend/projects/api/

# Install dependencies for this project
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
  pnpm install --filter "@javascript-example-backend/api..." --frozen-lockfile

# Start dev server
EXPOSE 3000
EXPOSE 5555
CMD ["pnpm", "--filter", "@javascript-example-backend/api", "run", "dev"]
